from .pbr_pix2pix import (
    NODE_CLASS_MAPPINGS as PIX2PIX_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as PIX2PIX_NAMES,
)
from .pbr_chained import (
    NODE_CLASS_MAPPINGS as CHAINED_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as CHAINED_NAMES,
)

# Merge all node mappings
NODE_CLASS_MAPPINGS = {**PIX2PIX_NODES, **CHAINED_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**PIX2PIX_NAMES, **CHAINED_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
